export const AU_IN_KM = 149597870.7

export const EMOJI = {
  ALIEN: '👽',
  ALIEN_MONSTER: '👾',
  ASTRONAUT_MAN: '👨‍🚀',
  ASTRONAUT_WOMAN: '👩‍🚀',
  COMET: '☄️',
  CRESCENT_MOON: '🌙',
  DIZZY_SYMBOL: '💫',
  EARTH_GLOBE_AMERICAS: '🌎',
  EARTH_GLOBE_ASIA_AUSTRALIA: '🌏',
  EARTH_GLOBE_EUROPE_AFRICA: '🌍',
  FIRST_QUARTER_MOON: '🌓',
  FIRST_QUARTER_MOON_FACE: '🌛',
  FLYING_SAUCER: '🛸',
  FULL_MOON: '🌕',
  GLOWING_STAR: '🌟',
  HOURGLASS_DONE: '⌛',
  HOURGLASS_NOT_DONE: '⏳',
  LAST_QUARTER_MOON: '🌗',
  LAST_QUARTER_MOON_FACE: '🌜',
  MILKY_WAY: '🌌',
  NEW_MOON: '🌑',
  NEW_MOON_FACE: '🌚',
  QUESTION_MARK: '❓',
  RINGED_PLANET: '🪐',
  ROBOT_FACE: '🤖',
  ROCK: '🪨',
  ROCKET: '🚀',
  SATELLITE: '🛰️',
  SHOOTING_STAR: '🌠',
  SPARKLES: '✨',
  STAR: '⭐',
  SUNRISE: '🌅',
  SUNRISE_OVER_MOUNTAINS: '🌄',
  SUN_WITH_FACE: '🌞',
  TELESCOPE: '🔭',
  VOLCANO: '🌋',
  WANING_CRESCENT_MOON: '🌘',
  WANING_GIBBOUS_MOON: '🌖',
  WAXING_CRESCENT_MOON: '🌒',
  WAXING_GIBBOUS_MOON: '🌔',
}

export const CELESTIAL_TYPES: Record<number, { name: string; emoji: string }> =
  {
    1: { name: 'star', emoji: EMOJI.STAR },
    2: { name: 'planet', emoji: EMOJI.RINGED_PLANET },
    3: { name: 'moon', emoji: EMOJI.CRESCENT_MOON },
    4: { name: 'belt', emoji: EMOJI.ROCK },
    5: { name: 'station', emoji: EMOJI.SATELLITE },
  }
